### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hyandell** [Sleepychord/CogLTX#12]
Hi @Sleepychord,

When looking at this project, I wasn't able to find a license. Is it under MIT like https://github.com/Sleepychord/cogdata, or is there a different license?

**Comment by Sleepychord** [comment]
That's Okay. I will add a MIT.

**Comment by hyandell** [comment]
Thanks @Sleepychord!

As I'm causing you effort, I went ahead and created a PR to hopefully mean you have less to do :)

**Comment by yogarshi** [comment]
Hi @Sleepychord. Any update on the license? Thanks!

**Comment by hyandell** [comment]
Closing :) Thank you @Sleepychord
