### ISSUE TITLE
Caching the score of Judge during training Judge?

### ISSUE THREAD

**Issue by juanguang** [Sleepychord/CogLTX#17]
If I'm understanding the code correctly, at the end of training_step in introspector code, it is updating the scores of Judge as suggest in the algorithm in the paper: "can be replaced by cached scores during training judge". However, training_step() is one batch instead of one epoch. The weights of Judge keep updating for batches. Shouldn't we calculate the score of Judge after Judge is fully trained inside one epoch?

**Comment by Sleepychord** [comment]
yes, what you said is the ideal method, but need re-evaluate the dataset. It is slow. "can be replaced " does not mean the values are exactly equal, but the final results are similar in the experiments.

**Comment by juanguang** [comment]
Got it. Thanks!
