### ISSUE TITLE
run_20news acc仅有0.81

### ISSUE THREAD

**Issue by yudong27** [Sleepychord/CogLTX#9]
作者提供的代码一直无法运行，经过多次调试，修正了代码里的问题，终于可以运行了，但20news的acc只有0.81，和文章中展示的0.87有差距
for long text: accuray 0.7934272300469484, total 1065

作者能否修复一下代码，或者提供一个docker，产出0.87的结果？

**Comment by Sleepychord** [comment]
主要是当时的依赖库大更新坏掉了，和一些超参的原因吧……抱歉我最近实在没有时间，三月到五月之间，我把这个project用新的代码翻新一下QAQ 翻新之后我再close这个issue吧

**Comment by yudong27** [comment]
谢谢

**Comment by yudong27** [comment]
又测了一次，acc有0.829了.。 默认的epochs是2， 我增加到10试试

**Comment by yudong27** [comment]
在增大epoch的情况下，最好的结果有0.84了

accuracy: 0.8402814657461498
for long text: accuray 0.8028169014084507, total 1065

**Comment by yudong27** [comment]
在epoch=10时，结果更好了
accuracy: 0.8491768454593733
for long text: accuray 0.8131455399061033, total 1065
还是没有达到0.87

**Comment by juanguang** [comment]
大哥有遇到 https://github.com/Sleepychord/CogLTX/issues/8 这个问题吗 我现在代码也跑不通

**Comment by Sleepychord** [comment]
感谢提醒，我忙于其他project了。我接下来一段时间会重新用新的pretrained model实现类似的模型来refresh这个project，这个代码基于的pytorch_lightning已经完全不是原来的样子了，确实有点难办。
